import { RiFontSize } from 'react-icons/ri';
import {AlignText} from './constants.js';

export const props = [
  {
    name: 'Spin Wheel',
    radius: 0.88,
    itemLabelRadius: 0.83,
    itemLabelRotation: 180,
    itemLabelAlign: AlignText.left,
    itemLabelColors: ['#000'],
    itemLabelBaselineOffset: -0.06,
    itemLabelFont: 'Times New Roman',
    itemLabelFontSizeMax: 16,
    lineWidth: 14,
    lineColor: '#000',
    isInteractive: false,
    rotation: 0,
    rotationSpeed:50,
    rotationSpeedMax:300,
    onRest: e => console.log(e),
    overlayImage: '/spingame/img/spin-wheel.svg',
    items: [
      {
        image: '/spingame/img/one.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#F535C9',
      },
      {
        image: '/spingame/img/two.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#1CE21B',
        labelColor: '#fff',
      },
      {
        image: '/spingame/img/three.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#EE22B9',
      },
      {
        image: '/spingame/img/four.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#61E128',
      },
      {
        image: '/spingame/img/five.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#F535C9',
      },
      {
        image: '/spingame/img/six.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#1CE21B',
      },
      {
        image: '/spingame/img/seven.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#EE22B9',
      },
      {
        image: '/spingame/img/eight.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#61E128',
      },
      {
        image: '/spingame/img/nine.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#F535C9',
      },
      {
        image: '/spingame/img/ten.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#1CE21B',
      },
      {
        image: '/spingame/img/eleven.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#EE22B9',
      },
      {
        image: '/spingame/img/twelve.svg',
        imageRadius: 0.65,
        imageScale: 0.4,
        weight: 0.4,
        backgroundColor: '#61E128',
      },
    ],
  },
]